"""Pure crystallographic helpers used by differentiable core stages."""

from diffBloch.core.adp import (
    cartesian_adp_to_star,
    cholesky_adp,
    cholesky_raw_from_adp,
    cif_adp_to_star,
    equivalent_isotropic_adp,
    isotropic_adp,
)
from diffBloch.core.constraints import apply_symmetry_mask, positive, unit_interval
from diffBloch.core.crystal import (
    cell_matrix_from_parameters,
    cell_volume,
    orientation_basis,
    reciprocal_cell,
    reflection_condition,
)
from diffBloch.core.dynamical import (
    BeamPlan,
    BlochSystem,
    StructureFactorGather,
    build_beam_plan,
    build_bloch_system,
    build_structure_factor_gather,
    energy2sigma,
    energy2wavelength,
    excitation_errors,
    gather_structure_factors,
    kappa,
    m_factors,
    structure_matrix,
    structure_matrix_prefactor,
    wavelength2energy,
    wavevector_magnitude,
)
from diffBloch.core.losses import l1, mse, rbragg, w_rbragg, weighted_mse
from diffBloch.core.products import (
    AlignedIntensities,
    AlignmentPlan,
    BlochSolution,
    PatternBatch,
    align,
    build_alignment_plan,
    intensities,
)
from diffBloch.core.reciprocal import (
    g_vector_lengths,
    g_vectors,
    gmax_mask,
    make_hkl_grid,
    ravel_hkl,
    reciprocal_space_gpts,
)
from diffBloch.core.scattering import (
    debye_waller_factor,
    lobato_form_factors,
    resolution_cutoff,
    structure_factors,
)
from diffBloch.core.solver import propagate
from diffBloch.core.symmetry import (
    AsuExpansionPlan,
    DuplicateSite,
    ExpandedAsu,
    build_asu_expansion_plan,
    expand_asu,
)

__all__ = [
    "AlignedIntensities",
    "AlignmentPlan",
    "AsuExpansionPlan",
    "BeamPlan",
    "BlochSolution",
    "BlochSystem",
    "DuplicateSite",
    "ExpandedAsu",
    "PatternBatch",
    "StructureFactorGather",
    "align",
    "apply_symmetry_mask",
    "build_alignment_plan",
    "build_asu_expansion_plan",
    "build_beam_plan",
    "build_bloch_system",
    "build_structure_factor_gather",
    "cell_matrix_from_parameters",
    "cell_volume",
    "cartesian_adp_to_star",
    "cholesky_adp",
    "cholesky_raw_from_adp",
    "debye_waller_factor",
    "energy2sigma",
    "energy2wavelength",
    "cif_adp_to_star",
    "equivalent_isotropic_adp",
    "excitation_errors",
    "expand_asu",
    "g_vector_lengths",
    "g_vectors",
    "gather_structure_factors",
    "gmax_mask",
    "intensities",
    "isotropic_adp",
    "kappa",
    "l1",
    "lobato_form_factors",
    "m_factors",
    "make_hkl_grid",
    "mse",
    "orientation_basis",
    "positive",
    "propagate",
    "ravel_hkl",
    "rbragg",
    "reciprocal_cell",
    "reciprocal_space_gpts",
    "reflection_condition",
    "resolution_cutoff",
    "structure_factors",
    "structure_matrix",
    "structure_matrix_prefactor",
    "unit_interval",
    "w_rbragg",
    "wavelength2energy",
    "wavevector_magnitude",
    "weighted_mse",
]
