"""Native orientation derivation pinned against a golden fixture.

Regenerate via the fixture's co-located ``generate_orientation_derivation_golden.py``. Oracle
independence lives in the golden; the native path under test re-derives the same orientations from
the UB/cell/angles.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from diffBloch.core.crystal import cell_matrix_from_parameters
from diffBloch.io import read_experimental_data
from diffBloch.preprocess import resolve_dataset_orientations
from diffBloch.preprocess.orientation import (
    busing_levy_matrix,
    compose_mosaic_tilts,
    goniometer_rotation,
    hexagonal_tilt,
    isotropic_mosaic_tilts,
    orientation_basis,
    orientation_matrices,
    rocking_curve_tilts,
    rotation_axis_correction,
    u_matrix,
)

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "quartz_anchor"


@pytest.fixture(scope="module")
def golden() -> dict[str, np.ndarray]:
    return dict(np.load(FIXTURES / "orientation_derivation_golden.npz"))


def test_orientation_matrices_match_golden(golden: dict[str, np.ndarray]) -> None:
    native = orientation_matrices(
        golden["ub_matrix"],
        golden["cell_params"],
        golden["alphas"],
        golden["betas"],
        golden["omegas"],
    )
    assert native.shape == golden["orientation_matrices"].shape == (99, 3, 3)
    # ~8.6e-7 residual: we compute the exact cell volume, not the PETS file's rounded
    # ``_cell_volume`` (113.32800 vs 113.32810) the golden derives from. Negligible, and intentional
    # (we do not reproduce the rounding). The convention itself -- order, B form, U = UB B^-1 -- is
    # exact.
    assert np.allclose(native, golden["orientation_matrices"], atol=1e-5)


def test_u_matrix_carries_the_cell_correction(golden: dict[str, np.ndarray]) -> None:
    # det(U) ~ 1.033: U = UB B^-1 folds the ~1% measured-vs-ideal cell correction, so U is NOT a
    # pure rotation. fit_orientation must preserve this (no re-orthonormalisation).
    u = u_matrix(golden["ub_matrix"], golden["cell_params"])
    assert np.linalg.det(u) == pytest.approx(1.03302, abs=1e-4)
    assert not np.allclose(u @ u.T, np.eye(3), atol=1e-2)


def test_rotation_axis_correction_is_a_proper_rotation() -> None:
    assert np.allclose(rotation_axis_correction(0.0), np.eye(3))
    r = rotation_axis_correction(272.994)
    assert np.allclose(r @ r.T, np.eye(3), atol=1e-12)
    assert np.linalg.det(r) == pytest.approx(1.0, abs=1e-12)
    # R_z(-theta) rotates x onto (cos(-theta), sin(-theta), 0).
    theta = np.deg2rad(272.994)
    assert np.allclose(r @ [1.0, 0.0, 0.0], [np.cos(-theta), np.sin(-theta), 0.0])


def test_orientation_matrices_stays_as_collected(golden: dict[str, np.ndarray]) -> None:
    """`orientation_matrices` applies no axis correction -- that is what the golden pins.

    The golden is generated by an independent implementation of the *as-collected* derivation, so
    this contract must not move when the goniometer-axis correction is introduced elsewhere.
    """
    import inspect

    assert "rotation_axis_position" not in inspect.signature(orientation_matrices).parameters


def test_resolved_orientations_are_the_golden_under_the_axis_correction() -> None:
    """The production path is exactly `R_z(-p)` applied to the as-collected golden."""
    record = read_experimental_data(FIXTURES / "exp_data.cif_pets")
    as_collected = orientation_matrices(
        record.ub_matrix,
        record.cell_parameters,
        record.alphas,
        record.betas,
        record.omegas,
    )

    resolved = resolve_dataset_orientations(record)

    position = record.rotation_axis_position_degrees
    assert position == pytest.approx(0.484)  # this fixture records a nonzero azimuth
    assert np.allclose(resolved, rotation_axis_correction(position) @ as_collected)
    assert not np.allclose(resolved, as_collected)  # the correction is not a no-op here


def test_resolve_dataset_orientations_requires_an_axis_position() -> None:
    """Absent is an error, not an assumed zero, and there is no way to override it."""
    record = read_experimental_data(FIXTURES / "exp_data.cif_pets")
    absent = record.model_copy(update={"rotation_axis_position_degrees": None})

    with pytest.raises(ValueError, match="rotation axis position"):
        resolve_dataset_orientations(absent)


def test_resolve_dataset_orientations_rejects_a_non_finite_azimuth() -> None:
    """PETS's free-text float grammar admits `nan`; it must not become an all-NaN orientation."""
    record = read_experimental_data(FIXTURES / "exp_data.cif_pets")
    poisoned = record.model_copy(update={"rotation_axis_position_degrees": float("nan")})

    with pytest.raises(ValueError, match="finite"):
        resolve_dataset_orientations(poisoned)
    with pytest.raises(ValueError, match="finite"):
        rotation_axis_correction(float("nan"))


def test_goniometer_rotation_is_a_proper_rotation() -> None:
    assert np.allclose(goniometer_rotation(0.0, 0.0, 0.0), np.eye(3))
    r = goniometer_rotation(-49.197, 3.5, 12.0)
    assert np.allclose(r @ r.T, np.eye(3), atol=1e-12)
    assert np.linalg.det(r) == pytest.approx(1.0, abs=1e-12)


def test_busing_levy_determinant_is_inverse_volume(golden: dict[str, np.ndarray]) -> None:
    a, b, c, alpha, beta, gamma = golden["cell_params"]
    ca, cb, cg = np.cos(np.deg2rad([alpha, beta, gamma]))
    volume = a * b * c * np.sqrt(1.0 - ca**2 - cb**2 - cg**2 + 2.0 * ca * cb * cg)
    assert np.linalg.det(busing_levy_matrix(golden["cell_params"])) == pytest.approx(1.0 / volume)


def test_orientation_basis_matches_oracle() -> None:
    # orientation_basis is the convention home; pin it against the (independently generated)
    # orientation oracle, which stored rotated reciprocal bases for known orientation matrices.
    oracle = np.load(FIXTURES / "orientation_oracle.npz")
    cell = cell_matrix_from_parameters(oracle["cellpar"])
    for k in range(oracle["orientation"].shape[0]):
        basis = orientation_basis(cell, oracle["orientation"][k])
        assert np.allclose(basis, oracle["rotated_reciprocal_basis"][k], atol=1e-12)


def test_invalid_shapes_raise(golden: dict[str, np.ndarray]) -> None:
    with pytest.raises(ValueError, match="cell_parameters must have shape"):
        busing_levy_matrix(np.ones(5))
    with pytest.raises(ValueError, match="ub_matrix must have shape"):
        u_matrix(np.ones((2, 2)), golden["cell_params"])
    with pytest.raises(ValueError, match="equal length"):
        orientation_matrices(
            golden["ub_matrix"], golden["cell_params"], np.zeros(3), np.zeros(2), np.zeros(3)
        )
    with pytest.raises(ValueError, match="shape"):
        orientation_basis(np.eye(3), np.ones((3, 2)))


def test_busing_levy_rejects_degenerate_cells() -> None:
    # Guard against poisoned inf/nan B matrices from invalid geometry (NumPy only warns otherwise).
    with pytest.raises(ValueError, match="finite"):
        busing_levy_matrix(np.array([5.0, 5.0, np.inf, 90.0, 90.0, 120.0]))
    with pytest.raises(ValueError, match="lengths must be positive"):
        busing_levy_matrix(np.array([5.0, 0.0, 5.0, 90.0, 90.0, 120.0]))
    with pytest.raises(ValueError, match=r"sin\(gamma\)"):
        busing_levy_matrix(np.array([5.0, 5.0, 5.0, 90.0, 90.0, 180.0]))
    with pytest.raises(ValueError, match="geometrically inconsistent"):
        busing_levy_matrix(np.array([5.0, 5.0, 5.0, 20.0, 20.0, 170.0]))


def test_isotropic_mosaic_tilts_are_proper_rotations_gaussian_placed() -> None:
    tilts, weights, polar = isotropic_mosaic_tilts(0.1, 5)
    assert tilts.shape == (5, 3, 3)
    assert weights.shape == (5,)
    assert polar.shape == (5,)
    assert np.allclose(np.linalg.det(tilts), 1.0)
    assert np.allclose(tilts @ np.swapaxes(tilts, 1, 2), np.eye(3))
    # Quantile (Rayleigh) placement, not a hard cutoff: samples reach past sigma with shrinking
    # weight, rather than all being confined within it.
    angle = np.rad2deg(
        np.arccos(np.clip((np.trace(tilts, axis1=1, axis2=2) - 1.0) / 2.0, -1.0, 1.0))
    )
    assert np.allclose(angle, polar)
    assert np.any(angle > 0.1)
    # Density weights fall off with distance from the pole: the farthest sample weighs the least.
    assert weights[np.argmax(angle)] == weights.min()
    assert np.all((weights > 0.0) & (weights <= 1.0))
    # Not all identical -- the samples actually scatter, not collapse to one point.
    assert not np.allclose(tilts[0], tilts[1])


def test_isotropic_mosaic_tilts_degenerate_cases_are_the_identity_with_unit_weight() -> None:
    tilts, weights, polar = isotropic_mosaic_tilts(0.1, 1)
    assert np.allclose(tilts, np.eye(3)[None])
    assert np.allclose(weights, [1.0])
    assert np.allclose(polar, [0.0])
    tilts, weights, polar = isotropic_mosaic_tilts(0.0, 5)
    assert np.allclose(tilts, np.eye(3)[None])
    assert np.allclose(weights, [1.0])
    assert np.allclose(polar, [0.0])


def test_isotropic_mosaic_tilts_rejects_invalid_inputs() -> None:
    with pytest.raises(ValueError, match="samples must be >= 1"):
        isotropic_mosaic_tilts(0.1, 0)
    with pytest.raises(ValueError, match="sigma_degrees must be non-negative"):
        isotropic_mosaic_tilts(-0.1, 5)


def test_compose_mosaic_tilts_is_every_rocking_tilt_times_every_mosaic_tilt() -> None:
    rocking = rocking_curve_tilts(1.0, 4)
    mosaic, _weights, _polar = isotropic_mosaic_tilts(0.1, 3)
    combined = compose_mosaic_tilts(rocking, mosaic)
    assert combined.shape == (12, 3, 3)
    assert np.allclose(np.linalg.det(combined), 1.0)
    # index = r * M + m: consecutive entries share a rocking tilt, mosaic varies fastest.
    for r in range(4):
        for m in range(3):
            assert np.allclose(combined[r * 3 + m], rocking[r] @ mosaic[m])


def test_rocking_curve_tilts_are_x_axis_rotations_spanning_the_semiangle() -> None:
    tilts = rocking_curve_tilts(1.0, 42)
    assert tilts.shape == (42, 3, 3)
    # Each tilt is a proper rotation about x: det = 1 and the x-axis is fixed.
    assert np.allclose(np.linalg.det(tilts), 1.0)
    assert np.allclose(tilts[:, 0, :], np.tile([1.0, 0.0, 0.0], (42, 1)))
    assert np.allclose(tilts[:, :, 0], np.tile([1.0, 0.0, 0.0], (42, 1)))
    # Endpoints are +/- semiangle about x; the span is symmetric.
    end = np.deg2rad(1.0)
    assert np.allclose(tilts[0], goniometer_rotation(-1.0, 0.0, 0.0))
    assert np.allclose(tilts[-1], goniometer_rotation(1.0, 0.0, 0.0))
    assert np.isclose(tilts[0, 2, 1], np.sin(-end))


def test_rocking_curve_tilts_unit_sampling_is_the_identity() -> None:
    # sampling = 1 puts the single tilt at angle 0 -> identity: the integration composes off.
    assert np.allclose(rocking_curve_tilts(1.0, 1), np.eye(3)[None])


def test_precession_tilts_sample_the_fixed_angle_cone() -> None:
    tilts = rocking_curve_tilts(1.0, 4, geometry="precession")
    assert tilts.shape == (4, 3, 3)
    assert np.allclose(np.linalg.det(tilts), 1.0)
    assert np.allclose(tilts @ np.swapaxes(tilts, 1, 2), np.eye(3))
    assert np.allclose(
        tilts,
        np.stack([hexagonal_tilt(azimuth, 1.0) for azimuth in (0.0, 90.0, 180.0, 270.0)]),
    )


def test_precession_unit_sampling_retains_the_cone_angle() -> None:
    # Unlike continuous rotation, one precession sample is the phi=0 cone orientation, matching
    # the legacy precession generator rather than silently turning integration off.
    assert np.allclose(
        rocking_curve_tilts(1.0, 1, geometry="precession"),
        hexagonal_tilt(0.0, 1.0)[None],
    )
